# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'DeepProProd' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeepProProd

  pod 'SwiftProtobuf', '~> 1.0'
  pod 'Alamofire', '~> 4.5'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RecordButton'
  pod 'DatePickerDialog'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'PRTween', '~> 0.0.1'
  pod 'Charts'
  pod 'ChartsRealm'
  pod 'SwiftGRPC'
  pod 'SwiftProtobuf', '~> 1.0'
  
end


target 'DeepProProdTests' do
use_frameworks!
  
  pod 'Mockingjay'
  pod 'Quick'
  pod 'Nimble'

end


workspace ‘DeepProProd’
